baseurl = "http://rday.leg.ufpr.br/"
languageCode = "pt"
title = "2º R Day"
theme = "vex-hugo"

[params]
  description = "2º R Day · 2019"

  # Put your custom stylesheets and scripts
  custom_stylesheets = ["./css/custom.css"]
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = "2º R Day"
    description = "Encontro de Usuários do R"

  # Navigation bar informations
  [params.navbar]
    # logo = "Home"
    [[params.navbar.menu]]
      link = "#"
      text = "Home"
    # [[params.navbar.menu]]
    #   link = "#programacao"
    #   text = "Atividades"
    # [[params.navbar.menu]]
    #   link = "#gallery"
    #   text = "Inscrições"
    # [[params.navbar.menu]]
    #   link = "#conferencistas"
    #   text = "Conferencistas"
    [[params.navbar.menu]]
      link = "downloads"
      text = "Downloads"
    [[params.navbar.menu]]
      link = "sobre"
      text = "Sobre"

  # Header
  [params.header]
    title = "2º R Day"
    subtitle = "Encontro de Usuários do R"
    theme = "Conectar e crescer a comunidade"
    # text = "Encontro de Usuários do R"
    text = '''<br/>

  * 13 de Dezembro de 2019
  * UFPR · Curitiba · Paraná
  * [rday.leg.ufpr.br](#)
           '''
    [params.header.image]
      path = "images/r-day-2-logo.png"
      alt = "2º Rday"
    [params.header.button]
      link = "./inscricao"
      text = "Fazer inscrição"

  # Features
  [params.features]
    title = "Atividades"
    [params.features.image]
      path = "images/programacao.png"
      alt = "Atividades"
    # Menu at the left of the image
    # [[params.features.left]]
    #   icon = "tf-ion-ios-alarm-outline"
    #   title = "Smooth Touch"
    #   text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"
    # [[params.features.left]]
    #   icon = "tf-ion-ios-bell-outline"
    #   title = "Elegant Design"
    #   text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"
    # [[params.features.left]]
    #   icon = "tf-ion-ios-cart-outline"
    #   title = "Easy Pricing"
    #   text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"
    # Menu at the right of the image
    [[params.features.right]]
      icon = "tf-ion-compass"
      title = "Conferências"
      text = "Sobre a importância e uso do R no âmbito de Ciência de Dados e Consultoria Estatística."
    [[params.features.right]]
      icon = "tf-ion-ios-cog"
      title = "Miniconferências"
      text = "A experiência de acadêmicos e profissionais sobre o uso do R em seus ambientes de trabalho, as tendências e oportunidades para colaboração e contribuição."
    [[params.features.right]]
      icon = "tf-ion-ios-chatboxes"
      title = "Mesa redonda"
      text = "Ao final do evento para debater formas de conectar a crescer a comunidade."

  [params.testimonials]
    title = "Conferencistas"
    [[params.testimonials.blocks]]
      text = "Título da conferência em breve"
      name = "Dan S. Reznik"
      position = "Customer-Facing Data Science & Analytics Consultant"
      image = "images/dan.jpg"
    [[params.testimonials.blocks]]
      text = "Título da conferência em breve"
      name = "Neale Ahmed El-Dash"
      position = "Diretor de pesquisas e consultor estatístico da SleekData"
      image = "images/neale.jpg"
    [[params.testimonials.blocks]]
      text = "Título da conferência em breve"
      name = "À confirmar"
      position = "Conferencista 3"
      image = "images/profile-female.png"
    [params.testimonials.button]
      link = "./inscricao"
      text = "Fazer inscrição"

  [params.promo]
    title = "Programação completa"
    text = '''
  Em breve estará disponível aqui
           '''
    [params.promo.image]
      path = "images/airport-690556_640.jpg"
      alt = "Programação completa"

  [params.feature_list]
    # title = "Desejar contribuir com o 2º R Day?"
    [[params.feature_list.items]]
      image = "images/achievement.jpg"
      title = "Seja um patrocinador"
      text = "O 2º R Day é um evento aberto, sem fins lucrativos e com inscrição gratuita. Seja um patrocinador do evento."
      button_link = "./sobre"
      button_text = "Ir para contato"
    # [[params.feature_list.items]]
    #   image = "images/showcase/showcase-3.png"
    #   title = "Lorem ipsum dolor sit amet."
    #   text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate, sed, assumenda. Tenetur sed esse, voluptas voluptate est veniam numquam, quis magni. Architecto minus suscipit quas, quo harum deserunt consequatur cumque!"
    #   button_link = ""
    #   button_text = "Check Features"

  [params.call_to_action]
    title = "Inscreva-se já!"
    text = "A inscrição é gratuita mas as vagas são limitadas."
    # placeholder = "Your Email Address Here"
    link = "./inscricao"
    button_text = "Fazer inscrição"

  [params.gallery]
    title = "Realização & apoio"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["leg.png", "dsbd.png", "pet.png", "ufpr.png", "coletum.png"]

  # Footer uses navbar data
